#!/bin/bash

# Reset Welcome Note Test Script
echo "🔄 Resetting Smart Notes to Show Welcome Note"
echo "=============================================="

echo "📱 Opening browser to test..."
echo ""
echo "🎯 To see the welcome note, open browser console and run:"
echo ""
echo "// Reset session and local storage"
echo "sessionStorage.removeItem('smartnotes-welcome-shown');"
echo "localStorage.removeItem('notes-app-data');"
echo "location.reload();"
echo ""
echo "OR run this one-liner:"
echo "sessionStorage.clear(); localStorage.clear(); location.reload();"
echo ""
echo "✨ This will:"
echo "1. Clear all session data"
echo "2. Clear all local storage data"  
echo "3. Reload the page"
echo "4. Show the welcome note automatically!"
echo ""
echo "🌟 The welcome note should now appear with:"
echo "• Beautiful gradient design"
echo "• Auto-selection on page load"
echo "• Animated welcome toast notification"
echo ""
echo "🔗 Open: http://localhost:5173"
